# -*- coding: utf-8 -*-
"""1. Limpieza de datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIIaSVFxiOX68XT-vWgYdEdoQtYwCCJk
"""

from google.colab import drive
drive.mount('/content/drive')

#Validación de ruta inicial
import os

print(os.listdir("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo"))

#Ubicación de archivos en drive personal

base_path = "/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/"
ruta_religioso = os.path.join(base_path, "Religioso")
ruta_cuentos = os.path.join(base_path,"Cuentos")
ruta_educativo = os.path.join(base_path,"Educativo")

print("Base:", os.listdir(base_path))
print("Religioso:", os.listdir(ruta_religioso))
print("Cuentos:", os.listdir(ruta_cuentos))
print("Educativo:", os.listdir(ruta_educativo))

#Método para leer archivos
def leer_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return [l.strip() for l in f.readlines() if l.strip()]

data = []

def cargar_dataset(ruta, nombre_dataset):

    archivos = os.listdir(ruta)

    # Español
    files_es = sorted([f for f in archivos if f.endswith(".es")])

    # Shipibo (puede ser .shi o .shp)
    files_shipibo = sorted([f for f in archivos if f.endswith(".shi") or f.endswith(".shp")])

    print(f"\n--- {nombre_dataset.upper()} ---")
    print("ES:", files_es)
    print("SHIPIBO:", files_shipibo)

    for f_es, f_shi in zip(files_es, files_shipibo):

        path_es = os.path.join(ruta, f_es)
        path_shi = os.path.join(ruta, f_shi)

        es_lines = leer_txt(path_es)
        shi_lines = leer_txt(path_shi)

        # Validación de alineación
        if len(es_lines) != len(shi_lines):
            print(f"Desalineado: {f_es}")
            print("ES:", len(es_lines), "| SHI:", len(shi_lines))
            continue

        for es, shi in zip(es_lines, shi_lines):
            data.append({
                "source": shi,
                "target": es,
                "dataset": nombre_dataset
            })

cargar_dataset(ruta_religioso, "religioso")
cargar_dataset(ruta_cuentos, "cuentos")
cargar_dataset(ruta_educativo, "educativo")

print("Total registros:", len(data))

import pandas as pd

corpus = pd.DataFrame(data)
corpus_original = corpus.copy()
print(corpus.shape)
corpus

# ----------------------------------------
# LIMPIEZA DE DATOS - SHIPIBO KONIBO
# ----------------------------------------

import re

# ----------------------------------------
# 1. Normalización básica
# ----------------------------------------
def limpiar_texto(texto):
    texto = texto.lower()                      # convertir a minúsculas
    texto = texto.strip()                      # eliminar espacios extremos
    texto = re.sub(r"\s+", " ", texto)         # normalizar espacios
    return texto

corpus["source"] = corpus["source"].apply(limpiar_texto)
corpus["target"] = corpus["target"].apply(limpiar_texto)


# ----------------------------------------
# 2. Eliminación de ruido (palabras sueltas)
# ----------------------------------------
def es_ruido(texto):
    return len(texto.split()) <= 1             # elimina palabras aisladas

corpus = corpus[
    ~corpus["source"].apply(es_ruido) &
    ~corpus["target"].apply(es_ruido)
]


# ----------------------------------------
# 3. Filtrado por longitud mínima (AJUSTADO)
# ----------------------------------------
corpus = corpus[
    (corpus["source"].str.len() > 2) &
    (corpus["target"].str.len() > 2)
]


# ----------------------------------------
# 4. Filtrado por desbalance (AJUSTADO)
# ----------------------------------------
corpus = corpus[
    abs(corpus["source"].str.len() - corpus["target"].str.len()) < 150
    #En Yine era 100 → más flexible para Shipibo
]


# ----------------------------------------
# 5. Eliminación de pares idénticos
# ----------------------------------------
corpus = corpus[
    corpus["source"] != corpus["target"]
]


# ----------------------------------------
# 6. Eliminación de duplicados
# ----------------------------------------
corpus = corpus.drop_duplicates()


# ----------------------------------------
# 7. Resetear índices
# ----------------------------------------
corpus = corpus.reset_index(drop=True)


# ----------------------------------------
# 8. Resultado final
# ----------------------------------------
print("Corpus limpio:", corpus.shape)

# ----------------------------------------
# MÉTRICAS DE CALIDAD DEL CORPUS - SHIPIBO
# ----------------------------------------

# Tamaño antes y después
total_original = len(corpus_original)
total_limpio = len(corpus)

# Cantidad eliminada
eliminados = total_original - total_limpio
porcentaje_eliminado = (eliminados / total_original) * 100

print("===== MÉTRICAS GENERALES =====")
print(f"Total original: {total_original}")
print(f"Total limpio: {total_limpio}")
print(f"Eliminados: {eliminados}")
print(f"% eliminado: {porcentaje_eliminado:.2f}%")


# ----------------------------------------
# LONGITUD PROMEDIO (POR IDIOMA)
# ----------------------------------------
print("\n===== LONGITUD PROMEDIO =====")

print("SHIPIBO original:", corpus_original["source"].str.len().mean())
print("ESPAÑOL original:", corpus_original["target"].str.len().mean())

print("SHIPIBO limpio:", corpus["source"].str.len().mean())
print("ESPAÑOL limpio:", corpus["target"].str.len().mean())


# ----------------------------------------
# DISTRIBUCIÓN POR DATASET
# ----------------------------------------
print("\n===== DISTRIBUCIÓN POR FUENTE =====")

print("ANTES:")
print(corpus_original["dataset"].value_counts())

print("\nDESPUÉS:")
print(corpus["dataset"].value_counts())


# ----------------------------------------
#  % ELIMINADO POR DATASET
# ----------------------------------------
print("\n===== ELIMINACIÓN POR DATASET =====")

for dataset in corpus_original["dataset"].unique():

    total_before = len(corpus_original[corpus_original["dataset"] == dataset])
    total_after = len(corpus[corpus["dataset"] == dataset])

    eliminados_ds = total_before - total_after

    if total_before > 0:
        porcentaje_ds = (eliminados_ds / total_before) * 100
    else:
        porcentaje_ds = 0

    print(f"{dataset}:")
    print(f"  Antes: {total_before}")
    print(f"  Después: {total_after}")
    print(f"  Eliminados: {eliminados_ds}")
    print(f"  % eliminado: {porcentaje_ds:.2f}%\n")

# ----------------------------------------
# VALIDACIÓN DEL CORPUS - SHIPIBO
# ----------------------------------------

print("\n===== EJEMPLOS DEL CORPUS =====")
print(corpus.sample(10))


# ----------------------------------------
# DISTRIBUCIÓN POR DATASET
# ----------------------------------------
print("\n===== DISTRIBUCIÓN POR DATASET =====")
print(corpus["dataset"].value_counts())


# ----------------------------------------
# LONGITUD PROMEDIO
# ----------------------------------------
print("\n===== LONGITUD PROMEDIO =====")
print("SHIPIBO:", corpus["source"].str.len().mean())
print("ESPAÑOL:", corpus["target"].str.len().mean())


# ----------------------------------------
# LONGITUD PROMEDIO POR DATASET
# ----------------------------------------
print("\n===== LONGITUD PROMEDIO POR DATASET =====")

for dataset in corpus["dataset"].unique():
    subset = corpus[corpus["dataset"] == dataset]

    print(f"\n{dataset}:")
    print("  SHIPIBO:", subset["source"].str.len().mean())
    print("  ESPAÑOL:", subset["target"].str.len().mean())


# ----------------------------------------
# DETECCIÓN DE POSIBLES ERRORES
# ----------------------------------------
print("\n===== POSIBLES PROBLEMAS =====")

# textos muy cortos
cortos = corpus[
    (corpus["source"].str.len() < 5) |
    (corpus["target"].str.len() < 5)
]

print("Ejemplos muy cortos:")
print(cortos.sample(min(5, len(cortos))))


# textos muy largos
largos = corpus[
    (corpus["source"].str.len() > 200) |
    (corpus["target"].str.len() > 200)
]

print("\n\n# de Ejemplos largos: ", len(largos))
print("\nEjemplos muy largos:")
print(largos.sample(min(5, len(largos))))

from sklearn.model_selection import train_test_split


# Train (80%) y temp (20%)
train, temp = train_test_split(
    corpus,
    test_size=0.2,
    random_state=42,
    stratify=corpus["dataset"]   # Mantiene proporción por dataset
)

# Validation (10%) y Test (10%)
val, test = train_test_split(
    temp,
    test_size=0.5,
    random_state=42,
    stratify=temp["dataset"]
)

# ----------------------------------------
# RESULTADOS
# ----------------------------------------
print("===== TAMAÑOS =====")
print("Train:", train.shape)
print("Val:", val.shape)
print("Test:", test.shape)

corpus.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/corpus.csv", index=False)
train.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/train.csv", index=False)
val.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/val.csv", index=False)
test.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/test.csv", index=False)

print("Datasets guardados ")