# -*- coding: utf-8 -*-
"""2. Tokenizacion_mBART50

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQdgubcHj4bav-sRd7qktr4GtfjHQg-W
"""

# =========================
# LIMPIEZA DE ENTORNO
# =========================

!pip uninstall -y tensorflow tensorflow-cpu tensorflow-gpu protobuf transformers peft accelerate -q

# =========================
# INSTALACIÓN BASE (COMPATIBLE)
# =========================

!pip install transformers==4.38.2 accelerate==0.27.2 protobuf==3.20.3 -q

# =========================
# MÉTRICAS
# =========================

!pip install evaluate sacrebleu unbabel-comet -q

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/train.csv"

df = pd.read_csv(path)
df = df[["source", "target"]].dropna()

import re

def limpiar_texto(texto):
    return re.sub(r"[^\w\s-]", "", texto)

#Aplicamos limpieza

df["source_clean"] = df["source"].apply(limpiar_texto)
df["target_clean"] = df["target"].apply(limpiar_texto)

"""# SILABIFICADOR"""

VOWELS = {'a', 'e', 'i', 'o'}

DIGRAPHS = {'ch', 'sh', 'ts'}

CODAS = {'n', 's', 'sh', 'x'}

def tokenize(word):
    tokens = []
    i = 0

    while i < len(word):

        if i + 1 < len(word) and word[i:i+2] in DIGRAPHS:
            tokens.append(word[i:i+2])
            i += 2
        else:
            tokens.append(word[i])
            i += 1

    return tokens

def silabificador_shipibo(word):

    tokens = tokenize(word)

    syllables = []
    current = []

    i = 0

    while i < len(tokens):

        current.append(tokens[i])

        # si es vocal
        if tokens[i] in VOWELS:

            # mirar siguiente
            if i + 1 < len(tokens):

                nxt = tokens[i + 1]

                # caso VCV
                if nxt not in VOWELS:

                    # mirar siguiente del siguiente
                    if i + 2 < len(tokens):

                        nxt2 = tokens[i + 2]

                        # VCV → dividir antes de consonante
                        if nxt2 in VOWELS:
                            syllables.append(current)
                            current = []

                        # VCCV
                        else:

                            # coda válida
                            if nxt in CODAS:
                                current.append(nxt)
                                syllables.append(current)
                                current = []
                                i += 1
                            else:
                                syllables.append(current)
                                current = []

                    else:
                        # final
                        if nxt in CODAS:
                            current.append(nxt)
                            i += 1

            syllables.append(current)
            current = []

        i += 1

    if current:
        syllables.append(current)

    return [''.join(s) for s in syllables]

def silabificar_texto(texto):
    """
    El silabificador trabaja palabra por palabra.

    Cada palabra:
    palabra → sílabas

    Luego todas las sílabas se unen
    en una sola secuencia.
    """

    palabras = texto.split()

    resultado = []

    for palabra in palabras:

        silabas = silabificador_shipibo(palabra)

        resultado.extend(silabas)

    return resultado

df["source_silabificado"] = df["source_clean"].apply(
    lambda x: " ".join(silabificar_texto(x))
)

for i in range(5):

    print("ORIGINAL:", df.iloc[i]["source"])

    print("LIMPIO:", df.iloc[i]["source_clean"])

    print("SILABIFICADO:", df.iloc[i]["source_silabificado"])

    print("TARGET:", df.iloc[i]["target_clean"])

    print("-----")

"""***Creación de dataset***"""

from datasets import Dataset

df_model = df[["source_silabificado", "target_clean"]].rename(
    columns={
        "source_silabificado": "source",
        "target_clean": "target"
    }
)

dataset = Dataset.from_pandas(df_model)

print(dataset)

print(dataset[0])

"""***Tokenización***"""

##Llamar al tokenizador de mBART50

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "facebook/mbart-large-50-many-to-many-mmt"
)

##Probar tokenización
'''
example = dataset[0]["source"]
example2 = dataset[0]["target"]

print("Texto:")
print(example)
print(example2)

tokens = tokenizer(example)
tokens2 = tokenizer(example2)

print("\nTokens:")
print(tokens["input_ids"])
print(tokens2["input_ids"])
'''

print("\n==============================")
print("COMPARACIÓN TOKENIZACIÓN")
print("==============================")

# Texto ORIGINAL limpio (SIN silabificador)
texto_original = df.iloc[0]["source_clean"]

# Texto CON silabificador
texto_silabificado = df.iloc[0]["source_silabificado"]

# =========================
# TOKENIZAR ORIGINAL
# =========================

tokens_original = tokenizer.tokenize(texto_original)
ids_original = tokenizer(texto_original)["input_ids"]

# =========================
# TOKENIZAR SILABIFICADO
# =========================

tokens_silab = tokenizer.tokenize(texto_silabificado)
ids_silab = tokenizer(texto_silabificado)["input_ids"]

# =========================
# MOSTRAR RESULTADOS
# =========================

print("\n--- TEXTO ORIGINAL ---")
print(texto_original)

print("\nTokens:")
print(tokens_original)

print("\nCantidad de tokens:")
print(len(tokens_original))

print("\nIDs:")
print(ids_original)

print("\n==============================")

print("\n--- TEXTO SILABIFICADO ---")
print(texto_silabificado)

print("\nTokens:")
print(tokens_silab)

print("\nCantidad de tokens:")
print(len(tokens_silab))

print("\nIDs:")
print(ids_silab)

## Función para tokenizar todo el dataset

def tokenizar_ejemplo(example):
    model_inputs = tokenizer(
        example["source"],
        max_length=64,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        example["target"],
        max_length=64,
        truncation=True,
        padding="max_length"
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

##Tokenizar todo el dataset

tokenized_dataset = dataset.map(tokenizar_ejemplo)