# -*- coding: utf-8 -*-
"""2. Tokenizacion_mBART50_v3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192BtI7LIQnbOx14qEJsWsnjwE5hBD5aG
"""

# =========================
# LIMPIEZA DE ENTORNO
# =========================

!pip uninstall -y tensorflow tensorflow-cpu tensorflow-gpu protobuf transformers peft accelerate -q

# =========================
# INSTALACIÓN BASE (COMPATIBLE)
# =========================

!pip install transformers==4.38.2 accelerate==0.27.2 protobuf==3.20.3 -q

# =========================
# MÉTRICAS
# =========================

!pip install evaluate sacrebleu unbabel-comet -q

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Shipibo Konibo/train.csv"

df = pd.read_csv(path)
df = df[["source", "target"]].dropna()

import re

def limpiar_texto(texto):
    return re.sub(r"[^\w\s-]", "", texto)

"""# SILABIFICADOR"""

#Silabificador v2, cambio en la forma de impresión de vacíos

VOWELS = {'a', 'e', 'i', 'o'}

DIGRAPHS = {'ch', 'sh', 'ts'}

CODAS = {'n', 's', 'sh', 'x'}

def tokenize(word):
    tokens = []
    i = 0

    while i < len(word):

        if i + 1 < len(word) and word[i:i+2] in DIGRAPHS:
            tokens.append(word[i:i+2])
            i += 2
        else:
            tokens.append(word[i])
            i += 1

    return tokens

def silabificador_shipibo(word):

    tokens = tokenize(word)

    syllables = []
    current = []

    i = 0

    while i < len(tokens):

        current.append(tokens[i])

        # si es vocal
        if tokens[i] in VOWELS:

            # mirar siguiente
            if i + 1 < len(tokens):

                nxt = tokens[i + 1]

                # caso VCV
                if nxt not in VOWELS:

                    # mirar siguiente del siguiente
                    if i + 2 < len(tokens):

                        nxt2 = tokens[i + 2]

                        # VCV → dividir antes de consonante
                        if nxt2 in VOWELS:
                            syllables.append(current)
                            current = []

                        # VCCV
                        else:

                            # coda válida
                            if nxt in CODAS:
                                current.append(nxt)
                                syllables.append(current)
                                current = []
                                i += 1
                            else:
                                syllables.append(current)
                                current = []

                    else:
                        # final
                        if nxt in CODAS:
                            current.append(nxt)
                            i += 1

            syllables.append(current)
            current = []

        i += 1

    if current:
        syllables.append(current)

    #print("SYLLABLES RAW:", syllables)

    return [''.join(s) for s in syllables if len(s) > 0]

#Aplicamos limpieza

df["source_clean"] = df["source"].apply(limpiar_texto)
df["target_clean"] = df["target"].apply(limpiar_texto)

from collections import Counter

# =========================
# EXTRAER SUBWORDS SHIPIBO
# =========================

subword_counter = Counter()

for texto in df["source_clean"]:

    palabras = texto.split()

    for palabra in palabras:

        # aplicar silabificador
        silabas = silabificador_shipibo(palabra)

        # contar sílabas/subwords
        subword_counter.update(silabas)

# mostrar más frecuentes
print("\nSUBWORDS MÁS FRECUENTES:")
print(subword_counter.most_common(50))

# =========================
# FILTRAR TOKENS ÚTILES
# =========================

nuevos_tokens = []

for token, freq in subword_counter.items():

    # evitar tokens demasiado pequeños
    if  freq >= 50:

        nuevos_tokens.append(token)

print("Cantidad de nuevos tokens:", len(nuevos_tokens))

print(nuevos_tokens[:50])

##Llamar al tokenizador de mBART50

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "facebook/mbart-large-50-many-to-many-mmt"
)

# =========================
# AGREGAR TOKENS SHIPIBO
# =========================

tokens_filtrados = []

for token in nuevos_tokens:

    if token not in tokenizer.get_vocab():

        tokens_filtrados.append(token)

print("Nuevos tokens reales:", len(tokens_filtrados))

tokens_agregados = tokenizer.add_tokens(tokens_filtrados)


print("Tokens agregados:", tokens_agregados)

texto = "matoki wishabo"

print("\nTEXTO DE PRUEBA:")
print(texto)

print("\nTOKENS:")
print(tokenizer.tokenize(texto))

print("\nIDS:")
print(tokenizer(texto)["input_ids"])

texto_prueba = df.iloc[0]["source_clean"]

tokens_silab = tokenizer.tokenize(texto_prueba)

print("\n==============================")
print("TOKENIZACIÓN FINAL")
print("==============================")

print("\nTexto:")
print(texto_prueba)

print("\nTokens:")
print(tokens_silab)

print("\nCantidad:")
print(len(tokens_silab))

print("\nIDs:")
print(tokenizer(texto_prueba)["input_ids"])

tokenizer.add_tokens(["comeriamos"])
print(tokenizer.tokenize("comeriamos"))

"""***Creación de dataset***"""

from datasets import Dataset

df_model = df[["source_clean", "target_clean"]].rename(
    columns={
        "source_clean": "source",
        "target_clean": "target"
    }
)

dataset = Dataset.from_pandas(df_model)

print(dataset)

print(dataset[0])

## Función para tokenizar todo el dataset

def tokenizar_ejemplo(example):
    model_inputs = tokenizer(
        example["source"],
        max_length=64,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        example["target"],
        max_length=64,
        truncation=True,
        padding="max_length"
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

##Tokenizar todo el dataset

tokenized_dataset = dataset.map(tokenizar_ejemplo)

##Limpiar el dataset de columnas iniciales

tokenized_dataset = tokenized_dataset.remove_columns(["source", "target"])
tokenized_dataset.set_format("torch")