# -*- coding: utf-8 -*-
"""1. Limpieza de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuAzVoQTftlir25ayCvP1eB-V7CZ2h7_
"""

from google.colab import drive
drive.mount('/content/drive')

#Validación de ruta inicial
import os

print(os.listdir("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Yine"))

#Ubicación de archivos en drive personal

base_path = "/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Yine/"
ruta_relatos = os.path.join(base_path, "Relatos")
ruta_historias = os.path.join(base_path,"Historias")

print("Base:", os.listdir(base_path))
print("Relatos:", os.listdir(ruta_relatos))
print("Historias:", os.listdir(ruta_historias))

#Método para leer archivos
def leer_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return [l.strip() for l in f.readlines() if l.strip()]

data = []

archivos_hist = os.listdir(ruta_historias)

files_es = sorted([f for f in archivos_hist if f.endswith(".es")])
files_pib = sorted([f for f in archivos_hist if f.endswith(".pib")])

print("ES:", files_es)
print("PIB:", files_pib)

for f_es, f_pib in zip(files_es, files_pib):
    path_es = os.path.join(ruta_historias, f_es)
    path_pib = os.path.join(ruta_historias, f_pib)

    es_lines = leer_txt(path_es)
    pib_lines = leer_txt(path_pib)


    if len(es_lines) != len(pib_lines):
        print(f"¡Desalineado!: {f_es}")
        print("Lineas español: ", len(es_lines))
        print("Lineas Yine: ", len(pib_lines))
        continue

    for es, yi in zip(es_lines, pib_lines):
        data.append({
            "source": yi,
            "target": es,
            "dataset": "historias"
        })
print(len(data))

#Cargar relatos

archivos_rel = os.listdir(ruta_relatos)

files_es_txt = sorted([f for f in archivos_rel if "dataset_es" in f])

print("Relatos ES:", files_es_txt)

for f_es in files_es_txt:
    f_yine = f_es.replace("dataset_es", "dataset_yine")

    path_es = os.path.join(ruta_relatos, f_es)
    path_yine = os.path.join(ruta_relatos, f_yine)

    if not os.path.exists(path_yine):
        print(f"¡Falta pareja!: {f_es}")
        continue

    es_lines = leer_txt(path_es)
    yine_lines = leer_txt(path_yine)

    if len(es_lines) != len(yine_lines):
        print(f"¡Desalineado!: {f_es}")
        continue

    for es, yi in zip(es_lines, yine_lines):
        data.append({
            "source": yi,
            "target": es,
            "dataset": "relatos"
        })

print(len(data))

#Creación de DataFrame uniendo las dos fuentes.

import pandas as pd

corpus = pd.DataFrame(data)
# Guardar copia del dataset original
corpus_original = corpus.copy()

print("Total dataset:", corpus.shape)
corpus

#Limpieza de datos

import re

# ----------------------------------------
# 1. Función de normalización básica
# ----------------------------------------
def limpiar_texto(texto):
    texto = texto.lower()                     # convertir a minúsculas (evita duplicados por mayúsculas)
    texto = texto.strip()                     # eliminar espacios al inicio y final
    texto = re.sub(r"\s+", " ", texto)        # reemplazar múltiples espacios por uno solo
    return texto

# Aplicar normalización
corpus["source"] = corpus["source"].apply(limpiar_texto)
corpus["target"] = corpus["target"].apply(limpiar_texto)


# ----------------------------------------
# 2. Eliminación de ruido (palabras sueltas)
# ----------------------------------------
def es_ruido(texto):
    return len(texto.split()) <= 1            # detecta textos de 1 palabra o menos

corpus = corpus[
    ~corpus["source"].apply(es_ruido) &       # eliminar si source es ruido
    ~corpus["target"].apply(es_ruido)         # eliminar si target es ruido
]


# ----------------------------------------
# 3. Filtrado por longitud mínima
# ----------------------------------------
corpus = corpus[
    (corpus["source"].str.len() > 3) &        # eliminar textos demasiado cortos (ej: "sí", "no")
    (corpus["target"].str.len() > 3)
]


# ----------------------------------------
# 4. Filtrado por desbalance de longitud
# ----------------------------------------
corpus = corpus[
    abs(corpus["source"].str.len() - corpus["target"].str.len()) < 100
    # elimina pares donde una frase es mucho más larga que la otra (posible desalineación)
]


# ----------------------------------------
# 5. Eliminación de pares idénticos
# ----------------------------------------
corpus = corpus[
    corpus["source"] != corpus["target"]      # evita casos donde no hay traducción real
]


# ----------------------------------------
# 6. Eliminación de duplicados
# ----------------------------------------
corpus = corpus.drop_duplicates()            # elimina pares repetidos exactos


# ----------------------------------------
# 7. Resetear índices
# ----------------------------------------
corpus = corpus.reset_index(drop=True)       # reordena índices después de eliminar filas


# ----------------------------------------
# 8. Resultado final
# ----------------------------------------
print("Corpus limpio:", corpus.shape)

# ----------------------------------------
# MÉTRICAS DE CALIDAD DEL CORPUS
# ----------------------------------------

# Tamaño antes y después
total_original = len(corpus_original)
total_limpio = len(corpus)

# Cantidad eliminada
eliminados = total_original - total_limpio
porcentaje_eliminado = (eliminados / total_original) * 100

print("----- MÉTRICAS DEL CORPUS -----")
print(f"Total original: {total_original}")
print(f"Total limpio: {total_limpio}")
print(f"Eliminados: {eliminados}")
print(f"% eliminado: {porcentaje_eliminado:.2f}%")

# ----------------------------------------
# LONGITUD PROMEDIO
# ----------------------------------------
print("\n----- LONGITUD PROMEDIO -----")
print("Yine original:", corpus_original["source"].str.len().mean())
print("Español original:", corpus_original["target"].str.len().mean())

print("Yine limpio:", corpus["source"].str.len().mean())
print("Español limpio:", corpus["target"].str.len().mean())

# ----------------------------------------
# DISTRIBUCIÓN POR DATASET
# ----------------------------------------
print("\n----- DISTRIBUCIÓN POR FUENTE -----")
print("ANTES:")
print(corpus_original["dataset"].value_counts())

print("\nDESPUÉS:")
print(corpus["dataset"].value_counts())

#Validación

print("\nEjemplos:")
print(corpus.sample(10))

print("\nDistribución por dataset:")
print(corpus["dataset"].value_counts())

print("\nLongitud promedio:")
print("Yine:", corpus["source"].str.len().mean())
print("Español:", corpus["target"].str.len().mean())

from sklearn.model_selection import train_test_split

train, temp = train_test_split(corpus, test_size=0.2, random_state=42)
val, test = train_test_split(temp, test_size=0.5, random_state=42)

print("Train:", train.shape)
print("Val:", val.shape)
print("Test:", test.shape)

corpus.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Yine/corpus.csv", index=False)
train.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Yine/train.csv", index=False)
val.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Yine/val.csv", index=False)
test.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Yine/test.csv", index=False)

print("Datasets guardados ")