# -*- coding: utf-8 -*-
"""1. Limpieza de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewa1v9KuSSfWtjx4lMe3eLtpv7UhzJyE
"""

from google.colab import drive
drive.mount('/content/drive')

#Validación de ruta inicial
import os

print(os.listdir("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Ashaninka"))

#Ubicación de archivos en drive personal

base_path = "/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Ashaninka/"
ruta_flashcards = os.path.join(base_path, "FlashCards")
ruta_cuentos = os.path.join(base_path,"Cuentos")


print("Base:", os.listdir(base_path))
print("Cuentos:", os.listdir(ruta_cuentos))
print("FlashCards:", os.listdir(ruta_flashcards))

#Método para leer archivos
def leer_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return [l.strip() for l in f.readlines() if l.strip()]

data = []

def cargar_cuentos_ashaninka(ruta, nombre_dataset):

    archivos = os.listdir(ruta)

    # Español
    files_es = sorted([f for f in archivos if f.endswith(".es")])

    # Asháninka / Ashéninka
    files_amazonico = sorted([
        f for f in archivos if f.endswith(".cni") or f.endswith(".cpu")
    ])

    print(f"\n--- {nombre_dataset.upper()} ---")
    print("ES:", files_es)
    print("ASHANINKA/ASHENINKA:", files_amazonico)

    # ----------------------------------------
    # EMPAREJAR ARCHIVOS POR NOMBRE EXACTO
    # ----------------------------------------
    pares = []

    for f_es in files_es:
        base_es = f_es.replace(".es", "")  # ej: es-cni1

        for f_am in files_amazonico:
            base_am = f_am.replace(".cni", "").replace(".cpu", "")

            # MATCH EXACTO
            if base_es == base_am:
                pares.append((f_es, f_am))

    print("Total pares encontrados:", len(pares))

    # Verificación extra (opcional pero recomendable)
    if len(pares) != len(files_es):
        print(" Advertencia: algunos archivos ES no tienen pareja")

    # ----------------------------------------
    # PROCESAR LOS PARES
    # ----------------------------------------
    for f_es, f_am in pares:

        path_es = os.path.join(ruta, f_es)
        path_am = os.path.join(ruta, f_am)

        es_lines = leer_txt(path_es)
        am_lines = leer_txt(path_am)

        # Validación de alineación
        if len(es_lines) != len(am_lines):
            print(f"Desalineado: {f_es} ↔ {f_am}")
            print("ES:", len(es_lines), "| AM:", len(am_lines))
            continue

        for es, am in zip(es_lines, am_lines):
            data.append({
                "source": am,
                "target": es,
                "dataset": nombre_dataset
            })

    print("Total ejemplos acumulados:", len(data))

cargar_cuentos_ashaninka(ruta_cuentos, "cuentos")

#Agregar FlashCards

import pandas as pd

def cargar_flashcards(ruta, nombre_dataset):

    archivos = os.listdir(ruta)

    files_xlsx = [f for f in archivos if f.endswith(".xlsx")]

    print(f"\n--- {nombre_dataset.upper()} ---")
    print("Total archivos:", len(files_xlsx))

    for file in files_xlsx:

        path = os.path.join(ruta, file)

        try:
            # Leer sin header (porque no hay encabezados)
            df = pd.read_excel(path, header=None)

            print(f"\nProcesando: {file}")

            # Tomar solo columnas A y B (0 y 1)
            df = df[[0, 1]]

            # Eliminar filas vacías
            df = df.dropna()

            for _, row in df.iterrows():

                es = str(row[0]).strip()
                am = str(row[1]).strip()

                # Evitar filas vacías o raras
                if es == "" or am == "":
                    continue

                data.append({
                    "source": am,
                    "target": es,
                    "dataset": nombre_dataset
                })

        except Exception as e:
            print(f"Error en {file}: {e}")

    print("Total ejemplos acumulados:", len(data))

cargar_flashcards(ruta_flashcards, "flashcards")

import pandas as pd

# ----------------------------------------
# CREAR DATAFRAME
# ----------------------------------------
corpus = pd.DataFrame(data)

print("Tamaño del corpus:", corpus.shape)
display(corpus)


# ----------------------------------------
# COPIA PARA MÉTRICAS (ANTES DE LIMPIEZA)
# ----------------------------------------
corpus_original = corpus.copy()

import re

# ----------------------------------------
# 1. NORMALIZACIÓN
# ----------------------------------------
def limpiar_texto(texto):
    texto = texto.lower()
    texto = texto.strip()
    texto = re.sub(r"\s+", " ", texto)
    return texto

corpus["source"] = corpus["source"].apply(limpiar_texto)
corpus["target"] = corpus["target"].apply(limpiar_texto)


# ----------------------------------------
# 2. ELIMINAR RUIDO (palabras sueltas)
# ----------------------------------------
def es_ruido(texto):
    return len(texto.split()) <= 1

corpus = corpus[
    ~corpus["source"].apply(es_ruido) &
    ~corpus["target"].apply(es_ruido)
]


# ----------------------------------------
# 3. FILTRADO POR LONGITUD (flexible)
# ----------------------------------------
corpus = corpus[
    (corpus["source"].str.len() > 2) &
    (corpus["target"].str.len() > 2)
]


# ----------------------------------------
# 4. FILTRADO POR DESBALANCE
# ----------------------------------------
corpus = corpus[
    abs(corpus["source"].str.len() - corpus["target"].str.len()) < 150
]


# ----------------------------------------
# 5. ELIMINAR PARES IDÉNTICOS
# ----------------------------------------
corpus = corpus[
    corpus["source"] != corpus["target"]
]


# ----------------------------------------
# 6. ELIMINAR DUPLICADOS
# ----------------------------------------
corpus = corpus.drop_duplicates()


# ----------------------------------------
# 7. RESET INDEX
# ----------------------------------------
corpus = corpus.reset_index(drop=True)


# ----------------------------------------
# RESULTADO
# ----------------------------------------
print("Corpus limpio:", corpus.shape)

# ----------------------------------------
# MÉTRICAS GENERALES
# ----------------------------------------
total_original = len(corpus_original)
total_limpio = len(corpus)

eliminados = total_original - total_limpio
porcentaje_eliminado = (eliminados / total_original) * 100

print("===== MÉTRICAS GENERALES =====")
print(f"Total original: {total_original}")
print(f"Total limpio: {total_limpio}")
print(f"Eliminados: {eliminados}")
print(f"% eliminado: {porcentaje_eliminado:.2f}%")


# ----------------------------------------
# LONGITUD PROMEDIO
# ----------------------------------------
print("\n===== LONGITUD PROMEDIO =====")

print("ASHANINKA original:", corpus_original["source"].str.len().mean())
print("ESPAÑOL original:", corpus_original["target"].str.len().mean())

print("ASHANINKA limpio:", corpus["source"].str.len().mean())
print("ESPAÑOL limpio:", corpus["target"].str.len().mean())


# ----------------------------------------
# DISTRIBUCIÓN POR DATASET
# ----------------------------------------
print("\n===== DISTRIBUCIÓN POR DATASET =====")

print("ANTES:")
print(corpus_original["dataset"].value_counts())

print("\nDESPUÉS:")
print(corpus["dataset"].value_counts())


# ----------------------------------------
# ELIMINACIÓN POR DATASET
# ----------------------------------------
print("\n===== ELIMINACIÓN POR DATASET =====")

for dataset in corpus_original["dataset"].unique():

    before = len(corpus_original[corpus_original["dataset"] == dataset])
    after = len(corpus[corpus["dataset"] == dataset])

    eliminados_ds = before - after
    porcentaje_ds = (eliminados_ds / before) * 100 if before > 0 else 0

    print(f"{dataset}:")
    print(f"  Antes: {before}")
    print(f"  Después: {after}")
    print(f"  Eliminados: {eliminados_ds}")
    print(f"  % eliminado: {porcentaje_ds:.2f}%\n")

from sklearn.model_selection import train_test_split

# Train (80%) y temp (20%)
train, temp = train_test_split(
    corpus,
    test_size=0.2,
    random_state=42,
    stratify=corpus["dataset"]   # mantiene proporción (cuentos vs flashcards)
)

# Validation (10%) y Test (10%)
val, test = train_test_split(
    temp,
    test_size=0.5,
    random_state=42,
    stratify=temp["dataset"]
)

# ----------------------------------------
# RESULTADOS
# ----------------------------------------
print("===== TAMAÑOS =====")
print("Train:", train.shape)
print("Val:", val.shape)
print("Test:", test.shape)

corpus.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Ashaninka/corpus.csv", index=False)
train.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Ashaninka/train.csv", index=False)
val.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Ashaninka/val.csv", index=False)
test.to_csv("/content/drive/MyDrive/Tesis 2/Entrenamiento modelos NMT/Ashaninka/test.csv", index=False)

print("Datasets guardados ")